version: "3.9"

services:
  db:
    image: postgres:15
    container_name: calday-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: calday
      POSTGRES_PASSWORD: calday123
      POSTGRES_DB: calday
    ports:
      - "7777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: calday-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data: