name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
      
    env:
        DATABASE_URL: postgresql://user:password@localhost:5432/db?schema=public
        REDIS_URL: redis://localhost:6379
        NEXTAUTH_SECRET: d6e3d2c0c6a564a2e8f79a61f6a9547036100229112b521cb1e0a704dweddddh
        NEXTAUTH_URL: http://localhost:3000
        STRIPE_SECRET_KEY: sk_test_51U1zU016a22NhhGw0yF1G9ZcRQPW5LEpaS0PKkg90UHhMNUvrwbkOQkC7GOWag0Dj7382vDtWVDPWXROQdLmrlSe00mnE2BeIo
        STRIPE_WEBHOOK_SECRET: whsec_72f4f0d8f4e2a00f4872c7a138c0383b804137e284d88b4402fd85f9384d0665
        STRIPE_PRO_PRICE_ID: price_1U2SCJ16a22NhhGwefJ6IUrw
        
        SKIP_ENV_VERIFICATION: 1

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        # Mapping Port จากเครื่องรัน (5432) เข้า Service (5432)
        ports:
          - 5432:5432
        # ตรวจสอบว่า Database พร้อมใช้งานหรือยังก่อนเริ่มรันขั้นตอนถัดไป
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
          image: redis:7-alpine
          ports:
            - 6379:6379
          options: >-
            --health-cmd redis-cli ping
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Lint
        run: npm run lint

      - name: Setup Test Database
        run: |
          npx prisma db push --accept-data-loss
          npx prisma db seed

      - name: Run Tests
        run: npm run test
        env:
          # ระบุว่าเป็นโหมดเทส
          NODE_ENV: test

      - name: Build project
        run: npm run build
          
